source "https://github.com/AmaniTechnologiesLtd/Mobile_SDK_Repo"
source "https://github.com/CocoaPods/Specs"

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# whatever this is, I don't like to change something under node_modules
# SPOILER ALERT: IT'S NOT 13.0 
# platform :ios, min_ios_version_supported
# That's better.
platform :ios, 13.0
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AmaniUiExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AmaniUiExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # dynamic_frameworks = ['AmaniSDK', 'AmaniUI', 'OpenSSL-Universal', 'lottie-ios', 'react-native-amani-ui']
  # pre_install do |installer|
  # installer.pod_targets.each do |pod|
  #     if !dynamic_frameworks.include?(pod.name)
  #       puts "Overriding the static_framework? method for #{pod.name}"
  #       def pod.static_framework?;
  #         true
  #       end
  #       def pod.build_type;
  #         Pod::BuildType.static_library
  #       end
  #     end
  #   end
  # end

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
        target.build_configurations.each do |config|
          # This block is for Xcode 15 updates
          if config.base_configuration_reference && Integer(xcode_base_version) >= 15
            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
          if target.name == 'AmaniSDK'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
          if target.name == 'AmaniUI'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
          if target.name == 'lottie-ios'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
        end
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
